# Generated by Django 4.2.7 on 2024-03-12 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sale_car_sale_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='car',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='client',
        ),
    ]
