# Generated by Django 4.2.7 on 2024-03-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_sale_car_remove_sale_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='car',
            field=models.ManyToManyField(related_name='car', to='main.car'),
        ),
        migrations.AddField(
            model_name='sale',
            name='client',
            field=models.ManyToManyField(related_name='client', to='main.client'),
        ),
    ]
